language: php

php:
  - 5.4
  - 5.6

env:
  global:
    - PLUGIN_NAME=BsHelpers
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.1
  matrix:
    - DB=mysql CAKE_VERSION=2.1
    - DB=mysql CAKE_VERSION=2.7

matrix:
  include:
    - php: 5.6
      env:
        - COVERALLS=1
    - php: 5.6
      env:
        - PHPCS=1 PHPCS_IGNORE="*/Test/*"
    - php: 5.6
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git -b master --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
